### ISSUE TITLE
StorageCluster Graceful Deletion

### ISSUE THREAD

**Issue by davidvossel** [openshift/ocs-operator#199]
When a StorageCluster is marked for deletion, we need to gracefully tear down the StorageCluster owned objects before the StorageCluster is completely removed from the cluster.

This can be achieved by using a finalizer on the StorageCluster object. A finalizer allows us to delay the deletion of the StorageCluster object until we've completely cleaned up all the cluster objects related to the Storage Cluster. We'd essentially be codifying some of the steps around removing the CephCluster, Noobaa core deployments, and StorageClassInitialization that the ```hack/cluster-cleanup.sh``` script performs today.

**Comment by sacharya** [comment]
Are you already working on this? I am in the middle of codifying the steps
in cluster-cleanup script, as I need it for uninstall/reinstall.

**Comment by davidvossel** [comment]
> Are you already working on this? I am in the middle of codifying the steps
in cluster-cleanup script, as I need it for uninstall/reinstall.

nope this isn't something I'm currently working on. I just made this issue for tracking purposes.

**Comment by davidvossel** [comment]
> in cluster-cleanup script, as I need it for uninstall/reinstall.

How are you approaching this? Are you using a finalizer on the StorageCluster, or codifying the cluster-clean script into the deploy-manager pkg just for functional test usage?

**Comment by sacharya** [comment]
I am just codifying the cluster-clean into deploy-manager pkg and using that from func test.

**Comment by davidvossel** [comment]
> I am just codifying the cluster-clean into deploy-manager pkg and using that from func test.

alrighty, i think that's a good start. That will probably end up being the basis of the storagecluster's deletion logic that makes its way into the operator reconcile loop at some point.

**Comment by bengland2** [comment]
When I run make cluster-clean, if I forget to clean up my application PVs beforehand then it hangs trying to delete them.   Seems like you could distinguish between PVs managed by OCS and PVs used by OCS.     At that point, only PVs used by OCS should be deleted.

IMO You shouldn't even allow deletion of a cluster that has OCS-managed PVs on it because they might have live data on them.    Make the user delete these PVs beforehand so it's their fault if data is destroyed.   Same with unmounting RBD or Cephfs volumes - make them tear down the pods before cluster-clean, when it's easy to do.    "I'm not going to delete your Ceph cluster if someone is still using it".

**Comment by mykaul** [comment]
I think the underlying PVs should have the retain policy set to save the PVs!
