### ISSUE TITLE
StorageCluster: Check for CephBlockPool before deploying NooBaa

### ISSUE THREAD

**Issue by jarrpa** [openshift/ocs-operator#245]
#244 introduced [a short sleep timer](https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/noobaa_system_reconciler.go#L55-L58) to compensate for the coordination between NooBaa and the Ceph volume it needs created. This is obviously a hack. We should de detecting whether or not the appropriate CephBlockPool is ready before going forward with the NooBaa deployment.

**Comment by jarrpa** [comment]
@travisn @davidvossel @guymguym @obnoxxx Pinging this on your radars.

**Comment by guymguym** [comment]
@jarrpa Can you explain why we need to wait at all?
Why not deploy noobaa with the expected ceph storage class and once it is ready the pods will start?

**Comment by davidvossel** [comment]
> Can you explain why we need to wait at all? Why not deploy noobaa with the expected ceph storage class and once it is ready the pods will start?

Right, I'd expect this to work. It would involve some rate limiting backoff to occur because of the retries, but eventually this scenario should succeed.

^ that's not the case though.  I think the real issue here is in rook/ceph. The reason we have that coordination between Noobaa and ceph is to work around an issue that occurs during PVC provisioning.  If the PVC is requested before the block pool is initialized internally in the ceph cluster, then it leads to the PVC being stuck in pending forever.

I think the NooBaa and ceph ordering helps give us more predictable setup timing. By only installing NooBaa after cephcluster initializes, we don't hit any exponential backoff when provisioning the PVC.  With respects to the PVC getting stuck in pending forever, the noobaa ceph ordering with the brief sleep call appears to be working around a rook issue.

**Comment by davidvossel** [comment]
Maybe to clarify a bit.

I'd keep the NooBaa ceph ordering as an optimization, but not as a fix to the rook PVC provisioning issue we're seeing. the issue here is with rook.

**Comment by guymguym** [comment]
Thanks @davidvossel !

**Comment by obnoxxx** [comment]
@davidvossel writes:
> I think the real issue here is in rook/ceph. The reason we have that coordination between Noobaa and ceph is to work around an issue that occurs during PVC provisioning. If the PVC is requested before the block pool is initialized internally in the ceph cluster, then it leads to the PVC being stuck in pending forever.

We might want to create a narrow test case for that (in rook?) and make that a blocker for our release...
