### ISSUE TITLE
OB/OBC CRDs are not owned by OCS downstream (although it bundles them)

### ISSUE THREAD

**Issue by guymguym** [openshift/ocs-operator#351]
CC @nimrod-becker @jarrpa @davidvossel 

Here is where it uses `required:` for these CRDs in the OCS CSV instead of using `owned:`
https://github.com/openshift/ocs-operator/blob/34106927774f51584ca6fa3b6ef4e9dc559db39e/deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml#L263-L302

This is because OCS CSV is copying the same `required` that NooBaa CSV is using upstream.

However for downstream these CRDs should be `owned` by OCS operator.

The reason it works is that the operator bundle includes those CRDs, which seems like a fishy situation, as OLM is not aware that OCS operator is the one owning those CRDs.

**Comment by tamireran** [comment]
I think we should have the OBC CRD separated, it would make sense from the community point of view. 
Since OCS is already using "require", my understanding is that we will just need to remove the CRDs from the OLM package and publish the lib-bucket-provisioner CSV to the community operators (downstream).
@guymguym  can handle the changes.
@jarrpa @obnoxxx please review so we can progress.

**Comment by jarrpa** [comment]
Agreed, I think that's why we ended up using `required` instead of `owned` in the first place.
