### ISSUE TITLE
Finalizer to ensure that Rook and Noobaa are removed before OCS-Operator

### ISSUE THREAD

**Issue by egafford** [openshift/ocs-operator#366]
When OCS-Operator is removed, uninstallation should complete with no orphaned resources that might block reinstallation. As such, OCS-Operator should ensure that its immediate dependent operators (Rook and Noobaa) are fully removed before allowing itself to be removed. In order to ensure this, we should add a Finalizer to the operator to validate that these deletions are complete before allowing its own removal. This Finalizer should not delete any dependent resources of Rook or Noobaa: they should remain responsible for all resources that they created through the uninstallation process.

**Comment by guymguym** [comment]
A finalizer on the OCS operator deployment? on the OCS CSV? Subscription?
I am not sure if a finalizer makes sense here.

Can you start by explaining which orphaned resources you are seeing when uninstalling using OLM?

**Comment by egafford** [comment]
At present, after removing the ocs-operator via OLM, any StorageClass with a provisioner in the set {openshift-storage.rbd.csi.ceph.com , openshift-storage.cephfs.csi.ceph.com , openshift-storage.noobaa.io/obc} should be deleted to allow reinstallation or terminating the OCS subscription. Sadly, it is not possible to automatically delete these classes and their dependent PV/PVCs and OB/OBCs, as this could easily result in unintentional loss of user data.

Most StorageClasses created by OCS are the responsibility of Rook and Noobaa. After some deliberation by @jarrpa, @obnoxxx, @rohantmp, and I, we arrived at a scheme of nesting finalizers in each operator (likely at the deployment level, as you suggest) to ensure that their dependent resources have been safely removed. While this may delay one-click removal of the operator, it will also prevent the user from believing that the operator is fully removed when there are still dependent resources to remove from the k8s cluster.

That being said, if you have a suggestion as to how to better facilitate the removal of OCS-operator via OLM while ensuring that its dependents are removed and that the user has thoughtfully removed or migrated their data, let's absolutely have that discussion.

**Comment by guymguym** [comment]
You are right that we cannot set the StorageClasses to have owner reference on StorageCluster because StorageClasses are global and OCS StorageCluster is namespaced, and setting owner reference this way causes the kubernetes garbage collector to go crazy and delete resources that it shouldn't.

However, OCS does deploy at least one cluster-wide resource - a ClusterRole. So how about we set the StorageClasses owner-reference to be the OCS ClusterRole? this way once OLM removed that cluster-role it will also remove all of the storage-classes.

Perhaps we can also use a less "accidental" resource for that purpose - we can include in the OCS OLM package one StorageClass with a `provisioner: kubernetes.io/no-provisioner` that will only serve as the parent for all the other StorageClasses and once OLM will delete it all the other will get garbage-collected as well.

**Comment by egafford** [comment]
Until we have a "soft vs. hard delete" option in OLM, I'm concerned that automated removal of StorageClasses (and the PVs/PVCs/OBs/OBCs based on them) could easily result in accidental user data loss. Avoiding accidental data loss was the reason we discussed using a finalizer pattern rather than an ownerRef-based automatic GC pattern.

Automatic removal of a single resource that cascades into removal of its dependents is certainly clean and simple, but asking the user to manually consider and manage the deletion of their resources is actually a feature here. Your suggestion definitely addresses the problem of ensuring dependency removal. Still, we can do the same with less risk of data loss with a finalizer model, though admittedly the code will be more complex.

**Comment by guymguym** [comment]
First - I think there's a misconception here - deleting StorageClasses is not going to effect existing PVs/PVCs/OBs/OBCs as the reference to the SC is weak (only by name).

I think that leaving manual work to the user can't really be classified as a feature.
If we want to help the user - we should allow undo, and I don't see how finalizers allow that.
Instead of adding a finalizer, we can just leave the data we don't want to loss and the result will be the same - the user will be forced to cleanup manually.
