### ISSUE TITLE
Finalizer to ensure that all managed StorageClusters are removed before OCS-Operator

### ISSUE THREAD

**Issue by egafford** [openshift/ocs-operator#367]
In order to ensure that uninstallation is complete after removal of OCS-Operator, we must ensure that no orphaned resources exist to block reinstallation. Dependent StorageClusters cannot be forcibly deleted due to risk of user data loss. As such, we should add a finalizer to OCS-Operator to ensure that all managed StorageClusters are deleted before allowing OCS-Operator itself to be deleted.

**Comment by guymguym** [comment]
Hey @egafford 

- To which CR you think this finalizer should be added to? The CSV? The operator deployment? An operator is not really one CR that represents it all. Perhaps only the OLM Subscription does it.

- Who will be responsible to remove the finalizer once all StorageClusters are deleted? The OCS operator itself? I think this might not be a good idea since it creates somewhat of a circular dependency.

- If the OLM also deletes the StorageCluster CRD when uninstalling the operator, then all StorageCluster CR's will get deleted as a result. But I am not sure exactly if OLM does that or plans to do it.

This is a common concern for every operator that manages a stateful application, so perhaps it should be supported by OLM somehow since OLM is handling uninstall of operators Subscription and CSV. For example OLM can have an option whether to delete all the resources that it owns or not when uninstalling.

**Comment by egafford** [comment]
@guymguym, I imagined that we would likely want to hang this finalizer on the ocs-operator deployment; it seems to be the most directly responsible point in the dependency graph. 

I agree that a deeper change to OLM may be warranted here, though. I'd be quite interested in working with the OpenShift OLM folks on a scheme to enable an cleaner operator removal path for operators that manage state. An option (even if just a simple yes-I-really-mean-it boolean) to perform a hard delete or a safe, managed delete would be a significant UX improvement. I'll pursue this as an option. Regardless, we'll need a finalizer to either hard delete dependent StorageClusters or refuse to complete deletion until all dependent StorageClusters are removed.

Does this sound reasonable?

**Comment by guymguym** [comment]
@egafford If the goal is to delete the StorageClusters when the OCS-operator is removed, then why not set the operator deployment as the StorageCluster owner?
