### ISSUE TITLE
Finalizer to ensure that all managed StorageClasses are removed before OCS-Operator

### ISSUE THREAD

**Issue by egafford** [openshift/ocs-operator#368]
In order to ensure that uninstallation is complete after removal of OCS-Operator, we must ensure that no orphaned resources exist to block reinstallation. Dependent StorageClasses cannot be forcibly deleted due to risk of user data loss. As such, we should add a finalizer to OCS-Operator to ensure that all managed StorageClasses are deleted before allowing OCS-Operator itself to be deleted.

Note that only StorageClasses with openshift-storage.rbd.csi.ceph.com, openshift-storage.cephfs.csi.ceph.com, and openshift-storage.noobaa.io/obc provisioners should be included in this test.

**Comment by brainfunked** [comment]
I have seen this behaviour on my cluster. I'm writing functional tests for validating this behaviour, which I'll send a PR for. The tests will pass once the finalizer is actually implemented.

**Comment by guymguym** [comment]
Hi @egafford 

Note that deleting StorageClasses shouldn't create any form of data-loss.
The reference from PV/PVC/OB/OBC to StorageClass is a weak reference that should only be used on provisioning time.

So in this case, if the issue is merely the cleanup of StorageClasses once the operator is finally removed, why not set the owner reference of the StorageClasses to be a global resources such as a ClusterRole that OLM removes automatically when uninstalling a operator CSV? Isn't it better that this cleanup will be made automatic?

**Comment by brainfunked** [comment]
@guymguym Your comment brings up a couple of interesting test scenarios. I'll run them manually first, to see what currently happens:

1. Ensure that there are bound PVs against a storage class created by the operator. Uninstall the operator.
2. Make PVCs against the storage classes left behind after the operator is uninstalled.

Do we already know what the 'correct' behaviour in such scenarios should be; especially the first one?

**Comment by brainfunked** [comment]
I've create a separate "negativetests" package to add tests that intend to break the cluster in various ways. This package should also be able to accommodate the tests I've mentioned above. Once #387 is reviewed, I could start implementing these tests.
