### ISSUE TITLE
Separate CSV generation out into its own repository

### ISSUE THREAD

**Issue by obnoxxx** [openshift/ocs-operator#427]
The primary purpose of this git repository is to host the code for the ocs-operator. But this repo also contains the code for generating the CSV for the OCS entry in the operator hub, which is a combination of ocs-operator, rook-ceph-operator, and noobaa-operator as long as the commited generated CSV data. This combination in one repository seems artificial and wrong to me. A cleaner approach would be to put the csv-generation code and the generated csv data into a separate repository that pulls the data from all three operators. This way, the development of the ocs-operator and the csv can be cleanly separated. It should make flows and responsibilities more obvious.

A possible place for the csv/registry code might be https://github.com/openshift/ocs-operator .

If we do this separation, then the whole e2e tests for the ocs product that pulls the whole set of ocs-operator, noobaa, and rook would move from this ocs-operator repository to the new repository, leaving only ocs-operator specific tests in this repo for CI.

**Comment by obnoxxx** [comment]
@jarrpa FYI

**Comment by guymguym** [comment]
@obnoxxx Can you describe one benefit from this separation?
I can think of several bad outcomes, and not good one.

**Comment by jarrpa** [comment]
@guymguym The biggest benefit is for actual ocs-operator engineering. Currently we face a lot of issues with rebases and backports due to CSV changes, often times just the hash file being incorrect. In addition, the CSVs generated on GitHub are not actually used for anything other than testing. Downstream generates its own CSVs and has slightly different requirements. We have no reason to actually keep records of CSVs on GitHub.

The only problem I see is that now development on the ocs-operator would require coordination between two repos. I don't think this would be any more of a hassle than what we have to do already, especially if we don't keep copies of the CSV with every commit and just generate it for every test.

**Comment by umangachapagain** [comment]
How about we just move CSV generation and Checksum validation out of the general workflow? and for basic CI tests?

That way we can still have CSV within this repo and not maintain it on per PR basis. We could just update it per release or when there are api changes or run nightly job to keep it in check maybe?

If there is a real strong need for a separate repo of the mentioned nature, we could just mirror our CSVs to it (something like what K8s does to all its sub projects). But, we'd still need to maintain CSV within this repo as that is what the operator-framework kind-of requires for CSV generation and there's more tooling being built around this assumption.
